### ISSUE TITLE
Allow passing constructor parameters to Grid

### ISSUE THREAD

**Issue by vaadin-miki** [vaadin-miki/super-template#11]
By default `Grid` is created in bean-less manner, which breaks a lot of methods. Find a way to initialise the `Grid` with proper bean class.

**Comment by anasmi** [comment]
For example, if user wants to set Items using `setItems` method a 
```
" Invocation of init method failed; nested exception is java.lang.UnsupportedOperationException: This method can't be used for a Grid that isn't constructed from a bean type. To construct Grid from a bean type, please provide a beanType argument the constructor: Grid<Person> grid = new Grid<>(Person.class)" ...
```

is thrown. A possible solution seems to be using https://vaadin.com/forum/thread/17626951/grid-properties-in-designer , but this breaks the @Id binding, so it would be great to have an "out-of-the-box" binding
